Name:           graph-rewriting-lib
Version:        0.7.9
Copyright:      (c) 2010, Jan Rochel
License:        BSD3
License-File:   LICENSE
Author:         Jan Rochel
Maintainer:     Efim Kubyshkin efimkub@mail.ru
Build-Type:     Simple
Synopsis:       Interface for port graph rewriting
Category:       Graphs
Cabal-Version:  >= 1.10
Extra-Source-Files: AUTHORS

Library
  Default-Language: Haskell2010
  Build-Depends:
    base >= 4.9 && < 5,
    base-unicode-symbols >= 0.2 && < 0.3,
    graph-rewriting >= 0.7.8 && < 0.9,
    containers >= 0.3 && < 0.7
  Exposed-Modules:
    GraphRewriting.Lib.Lib
  Other-Modules:
    GraphRewriting.Lib.Global
  Default-Extensions:
    UnicodeSyntax
  Other-Extensions:
    FlexibleInstances
    FlexibleContexts
    MultiParamTypeClasses
    TypeSynonymInstances
    OverlappingInstances
  GHC-Options:    -fno-warn-duplicate-exports -fwarn-unused-binds -fwarn-unused-imports -fwarn-unused-do-bind -fwarn-wrong-do-bind -fwarn-unrecognised-pragmas -fno-warn-tabs
